// MESSAGES
const SAVE_STATUS_ERROR_MESSAGE = 'No se pudo guardar la información';
const SAVE_STATUS_SUCCESS_MESSAGE = 'Se grabaron los datos correctamente';
const QUERY_STATUS_ERROR_MESSAGE = 'No se pudo obtener la información requerida';
const QUERY_STATUS_SUCCESS_MESSAGE = 'Información cargada correctamente';
const UPDATE_STATUS_ERROR_MESSAGE = 'No se pudo modificar la información';
const UPDATE_STATUS_SUCCESS_MESSAGE = 'Se modificaron los datos correctamente';
const DELETE_STATUS_ERROR_MESSAGE = 'No se pudo eliminar la información';
const DELETE_STATUS_SUCCESS_MESSAGE = 'Se eliminaron los datos correctamente';
const SERVER_ERROR = 'Ocurrión un error inesperado';
const SERVER_ERROR_UNAUTHORIZED = 'Se requieren permisos para acceder a esta información';
const USER_EXISTS = 'El usuario ingresado ya fue registrado';
const DATA_EXISTS = 'Los datos ingresados ya fueron registrados';

// CODE STATUS
const CODE_CONTINUE = 100;
const CODE_SWITCHING_PROTOCOLS = 101;
const CODE_PROCESSING = 102;
const CODE_EARLYHINTS = 103;
const CODE_OK = 200;
const CODE_CREATED = 201;
const CODE_ACCEPTED = 202;
const CODE_NO_AUTHORITATIVE = 203;
const CODE_NO_CONTENT = 204;
const CODE_RESET_CONTENT = 205;
const CODE_PARTIAL_CONTENT = 206;
const CODE_MULTI_STATUS = 207;
const CODE_ALREDY_REPORTED = 208;
const CODE_IM_USED = 226;
const CODE_MULTIPLE_CHOICES = 300;
const CODE_MOVED_PERMANENTLY = 301;
const CODE_FOUND = 302;
const CODE_SEE_OTHER = 303;
const CODE_NOT_MODIFIED = 304;
const CODE_USE_PROXY = 305;
const CODE_SWITCH_PROXY = 306;
const CODE_TEMPORARY_REDIRECT = 307;
const CODE_PERMANENT_REDIRECT = 308;
const CODE_BAD_REQUEST = 400;
const CODE_UNAUTHORIZED = 401;
const CODE_PAYMENT_REQUIRED = 402;
const CODE_FORBIDDEN = 403;
const CODE_NOT_FOUND = 404;
const CODE_METHOD_NOT_ALLOWED = 405;
const CODE_NOT_ACEPTABLE = 406;
const CODE_PROXY_AUTHENTICATION_REQUIRED = 407;
const CODE_REQUEST_TIMEOUT = 408;
const CODE_CONFLICT = 409;
const CODE_GONE = 410;
const CODE_LENGTH_REQUIRED = 411;
const CODE_PRECONDITION_FAILED = 412;
const CODE_PAYLOAD_TOO_LARGE = 413;
const CODE_URI_TOO_LONG = 414;
const CODE_UNSUPPORTED_MEDIA_TYPE = 415;
const CODE_RANGE_NOT_SATISFIABLE = 416;
const CODE_EXPECTATION_FAILED = 417;
const CODE_IAM_A_TEAPOT = 418;
const CODE_MISDIRECTED_REQUEST = 421;
const CODE_UNPROCESSABLE_ENTITY = 422;
const CODE_LOCKED = 423;
const CODE_FAILED_DEPENDENCY = 424;
const CODE_TOO_EARLY = 425;
const CODE_UPGRADE_REQUIERED = 426;
const CODE_PRECONDITION_REQUIRED = 428;
const CODE_TOO_MANY_REQUESTS = 429;
const CODE_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
const CODE_UNAVAILABLE_FOR_LEGAL_REASONS = 451;
const CODE_INTERNAL_SERVER_ERROR = 500;
const CODE_NOT_IMPLEMENTED = 501;
const CODE_BAD_GATEWAY = 502;
const CODE_SERVICE_UNAVAILABLE = 503;
const CODE_GETWAY_TIMEOUT = 504;
const CODE_HTTP_VERSION_NOT_SUPPORTED = 505;
const CODE_VARIANT_ALSO_NEGOTIATES = 506;
const CODE_INSUFFICIENT_STORAGE = 507;
const CODE_LOOP_DETECTED = 508;
const CODE_NOT_EXTENDED = 509;
const CODE_NETWORK_AUTHENTICATION_REQUIRED = 511;

const REQUEST_SUCCESS = "Successful";
const REQUEST_FAILED = "Failed";

module.exports = {
    SAVE_STATUS_ERROR_MESSAGE,
    SAVE_STATUS_SUCCESS_MESSAGE,
    QUERY_STATUS_ERROR_MESSAGE,
    QUERY_STATUS_SUCCESS_MESSAGE,
    UPDATE_STATUS_ERROR_MESSAGE,
    UPDATE_STATUS_SUCCESS_MESSAGE,
    DELETE_STATUS_ERROR_MESSAGE,
    DELETE_STATUS_SUCCESS_MESSAGE,
    SERVER_ERROR,
    SERVER_ERROR_UNAUTHORIZED,
    USER_EXISTS,
    DATA_EXISTS,
    CODE_CONTINUE,
    CODE_SWITCHING_PROTOCOLS,
    CODE_PROCESSING,
    CODE_EARLYHINTS,
    CODE_OK,
    CODE_CREATED,
    CODE_ACCEPTED,
    CODE_NO_AUTHORITATIVE,
    CODE_NO_CONTENT,
    CODE_RESET_CONTENT,
    CODE_PARTIAL_CONTENT,
    CODE_MULTI_STATUS,
    CODE_ALREDY_REPORTED,
    CODE_IM_USED,
    CODE_MULTIPLE_CHOICES,
    CODE_MOVED_PERMANENTLY,
    CODE_FOUND,
    CODE_SEE_OTHER,
    CODE_NOT_MODIFIED,
    CODE_USE_PROXY,
    CODE_SWITCH_PROXY,
    CODE_TEMPORARY_REDIRECT,
    CODE_PERMANENT_REDIRECT,
    CODE_BAD_REQUEST,
    CODE_UNAUTHORIZED,
    CODE_PAYMENT_REQUIRED,
    CODE_FORBIDDEN,
    CODE_NOT_FOUND,
    CODE_METHOD_NOT_ALLOWED,
    CODE_NOT_ACEPTABLE,
    CODE_PROXY_AUTHENTICATION_REQUIRED,
    CODE_REQUEST_TIMEOUT,
    CODE_CONFLICT,
    CODE_GONE,
    CODE_LENGTH_REQUIRED,
    CODE_PRECONDITION_FAILED,
    CODE_PAYLOAD_TOO_LARGE,
    CODE_URI_TOO_LONG,
    CODE_UNSUPPORTED_MEDIA_TYPE,
    CODE_RANGE_NOT_SATISFIABLE,
    CODE_EXPECTATION_FAILED,
    CODE_IAM_A_TEAPOT,
    CODE_MISDIRECTED_REQUEST,
    CODE_UNPROCESSABLE_ENTITY,
    CODE_LOCKED,
    CODE_FAILED_DEPENDENCY,
    CODE_TOO_EARLY,
    CODE_UPGRADE_REQUIERED,
    CODE_PRECONDITION_REQUIRED,
    CODE_TOO_MANY_REQUESTS,
    CODE_REQUEST_HEADER_FIELDS_TOO_LARGE,
    CODE_UNAVAILABLE_FOR_LEGAL_REASONS,
    CODE_INTERNAL_SERVER_ERROR,
    CODE_NOT_IMPLEMENTED,
    CODE_BAD_GATEWAY,
    CODE_SERVICE_UNAVAILABLE,
    CODE_GETWAY_TIMEOUT,
    CODE_HTTP_VERSION_NOT_SUPPORTED,
    CODE_VARIANT_ALSO_NEGOTIATES,
    CODE_INSUFFICIENT_STORAGE,
    CODE_LOOP_DETECTED,
    CODE_NOT_EXTENDED,
    CODE_NETWORK_AUTHENTICATION_REQUIRED,
    REQUEST_SUCCESS,
    REQUEST_FAILED
}